### ISSUE TITLE
Issue when using ffbwrap command

### ISSUE THREAD

**Issue by mokiman210** [berarma/ffbtools#15]
Game: Dirt Rally 2.0
Proton 4.2-9
Logitech G-29 in PS3 mode
Mint 19.3 Cinnamon
kernel: 5.0.0-37-generic

The new-lg4ff-0.2b driver has been compile and installed. It shows that it is active by lsmod when the wheel is plugged in. I extracted ffbtools to /home/user/drivers folder which created the ffbtools-master directory under that. I compiled it with the 'make' command and no errors were returned. I then tried to run the ffbwrap script from the ffbtools-master folder as described in the ffbwrap.md doc like so: ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- <command>  (no quotes). I immediately get: "bash: syntax error near unexpected token `newline'". What am I doing wrong? Thanks!

**Comment by jotomo** [comment]
You omitted the _command_ part at the end it seems.
To run DR2 through Steam, follow the last example in the referenced file.

**Comment by mokiman210** [comment]
Oops. I accidentally erased <command> when I created the above post. The "-- <command>" suffix was actually there when I tried it in a terminal. I've since tried adding the ffbwrap --update-fix /<proper path> -- <command> (replacing <command> with %command%) in the the game's (Dirt Rally 2) Properties - Set Launch Options window but that didn't work either.

**Comment by jotomo** [comment]
The `<command>` is a placeholder for the command the wrapper shall start.
However, for Dirt Rally 2.0, you need to use Steam to start the game. To that end, open the game's properties, click _Set launch options_ and enter this (replace _user_ with your actual user):
```
/home/user/drivers/ffbwrap-master/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick  -- %command%
```
This will make Steam invoke the wrapper, which in turn will call `%command%` which Steam will substitute with the game's binary.

**Comment by mokiman210** [comment]
Yes, I've already tried placing the call to the script _exactly_ like how you describe (with the correct user name, of course) in the game's launch options in Steam and nothing happened. Ffb still does not work. But shouldn't the script at least function from the terminal without returning a bash syntax error?  Why is that happening?

**Comment by berarma** [comment]
@mokiman210, the error you describe in your first message is most probably because you put the command inside <>. What happens when you don't use the <> characters in the command line?

In the last example from @jotomo, it's not just the user name you have to change but the full command path to match where ffbwrap is in your system.

Please, check everything above and if it still doesn't work please post the full commands and output to the make command, and also to the command: `bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick  -- bin/ffbplay`

**Comment by mokiman210** [comment]
Thank you for responding. Yes, I am aware that the command in _set Launch Options_ has to be the full path. I will post the results of your suggestions as soon as I can tomorrow. Thanks!

**Comment by mokiman210** [comment]
"<command>"

**Comment by mokiman210** [comment]
`<delete>`

**Comment by mokiman210** [comment]
In the terminal, when I executed the command: `bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- command` (from the ffbtools-master directory) I do not get the bash syntax error or any other message but nothing happens. The force feedback does not turn on.

If I enter `bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- bin/ffbplay` I get:

`ERROR: ld.so: object '/home/curt/Documents/Logitech_G29_Driver/ffbtools-master/bin/../build/libffbwrapper-i386.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Syntax: bin/ffbplay <device>`  (and nothing happens).

When I execute "make" now from the ffbtools-master directory I get:
"make: Nothing to be done for 'all'".

I looked through the logs for the terminal output for when I first executed the "make" command but was unable to locate anything.

Should I be substituting something for "%command%" when I enter the ffbwrap command in the "Set Launch Options" in Steam? This is unclear to me. 

Thanks!

**Comment by berarma** [comment]
> Should I be substituting something for "%command%" when I enter the ffbwrap command in the "Set Launch Options" in Steam? This is unclear to me.

Yes, you must use "%command%" as the command (without the quotes but with the %). Evertyhing up to this point sounds right. There's no issue.

> Edit: I also wanted to mentioned that I noticed today that if the wheel is plugged in to the USB port when I boot the machine, force feedback is turned on and working when I get to the desktop. FFB stays on until I start DR2 then drops out. If I plug the wheel in after I boot and get to the desktop the wheel initializes normally but there is no ffb.

This seems unrelated. You should look into dmesg and lsmod to see how the module is loaded.

**Comment by mokiman210** [comment]
Here is the exact text I enter into "Set Launch Options" in Steam: `/home/curt/Documents/Logitech_G29_Driver/ffbtools-master/bin/ffbwrap --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- %command%`
When I start the game force feedback does not get enabled. Any idea why it isn't working?

**Comment by leillo1975** [comment]
It's very strange. Check the configuration in game

**Comment by berarma** [comment]
I see you're using an old Proton version. Upgrade!

Closing since there's no issue in ffbwrap.

**Comment by mokiman210** [comment]
Where do you see I'm not using the latest version of Proton? I see that Proton 4.2-9 is selected in the game properties. Is that not the latest version? It's a new (3 weeks) installation and Proton 4.2-9 is the latest according to Steam, I believe.

**Comment by leillo1975** [comment]
The last version is 4.11-12

**Comment by berarma** [comment]
Some serious FFB issues were fixed in 4.11-10.

**Comment by berarma** [comment]
Since you seem to still have problems with the latest Proton version let's move the discussion here.

Which Proton version are you using now?

What does it happen exactly? Does the game launch?
Try the following in the Steam launcher options: /home/curt/Documents/Logitech_G29_Driver/ffbtools-master/bin/ffbwrap --logger=/home/curt/Documents/dr2 --update-fix /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick -- %command%

This should create a file at /home/curt/Documents/dr2-*

Could you attach this file?

**Comment by mokiman210** [comment]
[dr2-20200118140203.log](https://github.com/berarma/ffbtools/files/4081500/dr2-20200118140203.log)
Proton version is now 4.11-12.
The game starts and works perfectly with the wheel except for the lack of force feedback.
Thank you for continuing to assist me.

**Comment by berarma** [comment]
The update fix is in effect but the game isn't sending any FFB to the wheel. Most probably there's something wrong with the game configuration. Check that the FFB is correctly configured in-game.

**Comment by mokiman210** [comment]
There seems to be something wrong with Proton 4.11-12, possibly corrupted. I thought the wheel was working in the game with Proton 4.11 earlier but when I test it now, the bindings are messed up and weird things are happening (can steer right but not left). When I look at "Options&Extras/Input/Connected Device - Steering Wheel/Advanced Settings, "Device Type" is now grayed out and input bindings are scrambled. Wheel calibration ignores some of the inputs like throttle and clutch. And, of course, ffb is non-functional.
If I run the game under Proton 4.2-9 the wheel works properly, just no ffb. 

So, it looks like I may have to do a reinstall but the problem clearly is not the ffb driver. I appreciate your assistance and patience with me on this issue. Thanks again!

**Comment by berarma** [comment]
Honestly I think there's something wrong in your system. Maybe reinstalling Steam will solve it. Since Steam/Proton is pretty self-contained it usually just works or doesn't work at all, something in between isn't that common. If it doesn't work you can try reporting to the Proton project or use the Steam forums, you'll find more knowledgeable people there.

Also, try the wheel with some other software to make sure that's not the problem. Sometimes a loose wire,some USB connectors or a hub can make it fail.

Since the game can work with FFB just using the driver in the kernel and ffbwrap, I would recommend trying it this way. When you get it working you can try new-lg4ff for some improvement.

I hope you can fix it.
